version: "3.9"
services:
  social-events-db:
    image: postgres:14.0-alpine
    volumes:
      - /social-events/${ENVT}/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${SOCIAL_EVENTS_POSTGRES_DB}
      - POSTGRES_USER=${SOCIAL_EVENTS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SOCIAL_EVENTS_POSTGRES_PASSWORD}
  social-events-api:
    image: longmont.iguzman.com.mx:5000/social-events:1.0
    environment:
      - SECRET_KEY=${SOCIAL_EVENTS_SECRET_KEY}
      - ENVT=${ENVT}
      - DB_NAME=${SOCIAL_EVENTS_POSTGRES_DB}
      - DB_USER=${SOCIAL_EVENTS_POSTGRES_USER}
      - DB_PASSWORD=${SOCIAL_EVENTS_POSTGRES_PASSWORD}
      - EMAIL_HOST_USER=${SOCIAL_EVENTS_EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${SOCIAL_EVENTS_EMAIL_HOST_PASSWORD}
      - BRANCH_NAME=${BRANCH_NAME}
    volumes:
      - /social-events/${ENVT}/static:/static
      - /social-events/${ENVT}/media:/media
    ports:
      - "4030:8000"
    depends_on:
      - social-events-db
