# Generated by Django 3.2.7 on 2021-09-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agenda_items',
            field=models.ManyToManyField(blank=True, help_text='Exposiciones del evento', related_name='event_agenda', to='event.EventAgenda', verbose_name='Elementos de agenda'),
        ),
    ]
