# Generated by Django 3.2.7 on 2021-09-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_agenda_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expositor',
            name='short_description',
            field=models.CharField(blank=True, help_text='Descripción corta (90 carácteres)', max_length=90, null=True, verbose_name='Descripción corta del expositor'),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Nombre del expositor'),
        ),
    ]
