# Generated by Django 3.2.7 on 2021-09-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210930_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventagenda',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agenda'},
        ),
    ]
