# Generated by Django 3.2.7 on 2021-10-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_eventagenda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpicture',
            options={'verbose_name': 'Foto del evento', 'verbose_name_plural': 'Fotos de evento'},
        ),
    ]
