# Generated by Django 3.2.7 on 2021-10-01 02:44

import common.models.picture
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import event.models.event_user_registration
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_eventpicture_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Link del Facebook del Evento', max_length=256, null=True, verbose_name='Facebook del Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Link del Instagram del Evento', null=True, verbose_name='Instagram del Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='twitter_link',
            field=models.URLField(blank=True, help_text='Link del Twitter del Evento', null=True, verbose_name='Twitter del Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Link del Youtube del Evento', null=True, verbose_name='Youtube del Evento'),
        ),
        migrations.CreateModel(
            name='EventUserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Define si este registro estará habilitado', verbose_name='Registro habilitado')),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Índice númerico de ordenamiento de este registro', null=True, verbose_name='índice de ordenamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, default='Descripción', null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, size=[512, 512], upload_to=common.models.picture.picture)),
                ('check_in_complete', models.BooleanField(default=False, verbose_name='Check in completo?')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('zone', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('covid_test_result', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, size=[1920, 1920], upload_to=event.models.event_user_registration.picture)),
                ('responsive_letter', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, size=[1920, 1920], upload_to=event.models.event_user_registration.picture)),
                ('emergency_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Registro de usuario al evento',
                'verbose_name_plural': 'Registros de usuarios al evento',
                'unique_together': {('email', 'event')},
            },
        ),
    ]
