# Generated by Django 3.2.7 on 2021-10-01 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20211001_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuserregistration',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventuserregistration',
            name='href',
        ),
        migrations.RemoveField(
            model_name='eventuserregistration',
            name='img_picture',
        ),
        migrations.RemoveField(
            model_name='eventuserregistration',
            name='title',
        ),
    ]
