# Generated by Django 3.2.7 on 2021-10-01 02:48

from django.db import migrations
import django_resized.forms
import event.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20211001_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='responsive_letter',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[1920, 1920], upload_to=event.models.event.event_pictures),
        ),
    ]
