# Generated by Django 3.2.7 on 2021-10-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_responsive_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Mexico City', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='location',
            field=models.CharField(default='Hall A', max_length=32),
            preserve_default=False,
        ),
    ]
