# Generated by Django 3.2.7 on 2021-10-02 22:35

from django.db import migrations, models
import django_resized.forms
import event.models.event_agenda


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20211001_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventagenda',
            options={'verbose_name': 'Conferencia', 'verbose_name_plural': 'Conferencias'},
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default='2021-10-10', verbose_name='Fecha de fin del evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2021-10-15', verbose_name='Fecha de inicio del evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='date',
            field=models.DateField(verbose_name='Fecha de la conferencia'),
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='ending_time',
            field=models.TimeField(verbose_name='Fin de la conferencia'),
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='map',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Mapa de la conferencia', keep_meta=True, null=True, quality=90, size=[1920, 1080], upload_to=event.models.event_agenda.event_pictures, verbose_name='Mapa'),
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='pictures',
            field=models.ManyToManyField(blank=True, help_text='Fotos de la conferencia', related_name='event_agenda_pictures', to='event.EventPicture', verbose_name='Fotos de la conferencia'),
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='starting_time',
            field=models.TimeField(verbose_name='Inicio de la conferencia'),
        ),
    ]
