# Generated by Django 3.2.7 on 2021-10-04 03:17

from django.db import migrations
import django_resized.forms
import event.models.event_user_registration


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20211003_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuserregistration',
            name='img_user',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[1080, 1080], upload_to=event.models.event_user_registration.picture),
        ),
    ]
