# Generated by Django 3.2.7 on 2021-10-04 18:35

from django.db import migrations
import django_resized.forms
import event.models.event
import event.models.event_user_registration


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_eventuserregistration_img_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img_logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', help_text='Logo del evento', keep_meta=True, null=True, quality=100, size=[256, 128], upload_to=event.models.event.event_pictures, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='responsive_letter',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[1920, 1080], upload_to=event.models.event.event_pictures),
        ),
        migrations.AlterField(
            model_name='eventuserregistration',
            name='img_covid_test_result',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, size=[1920, 1080], upload_to=event.models.event_user_registration.picture),
        ),
        migrations.AlterField(
            model_name='eventuserregistration',
            name='img_signed_responsive_letter',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=90, size=[1920, 1080], upload_to=event.models.event_user_registration.picture),
        ),
        migrations.AlterField(
            model_name='eventuserregistration',
            name='img_user',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[1920, 1080], upload_to=event.models.event_user_registration.picture),
        ),
    ]
