# Generated by Django 3.2.7 on 2021-10-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20211004_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='check_in_pin',
            field=models.CharField(default='1234', max_length=4, verbose_name='Pin de 4 digitos para el Check in'),
            preserve_default=False,
        ),
    ]
