# Generated by Django 3.2.7 on 2021-10-04 21:54

from django.db import migrations
import django_resized.forms
import event.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20211004_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img_badge',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Imágen para fondo del gafete', keep_meta=True, null=True, quality=90, size=[512, 512], upload_to=event.models.event.event_pictures, verbose_name='Imágen para fondo del gafete'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img_cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Imágen Cover del evento', keep_meta=True, null=True, quality=90, size=[512, 512], upload_to=event.models.event.event_pictures, verbose_name='Imágen Cover'),
        ),
        migrations.AlterField(
            model_name='event',
            name='map',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Mapa del evento', keep_meta=True, null=True, quality=90, size=[1920, 1920], upload_to=event.models.event.event_pictures, verbose_name='Mapa'),
        ),
        migrations.AlterField(
            model_name='event',
            name='responsive_letter',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[1920, 1920], upload_to=event.models.event.event_pictures),
        ),
    ]
