# Generated by Django 3.2.7 on 2021-10-04 23:37

from django.db import migrations
import django_resized.forms
import event.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20211004_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img_cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Imágen Cover del evento', keep_meta=True, null=True, quality=90, size=[1920, 1080], upload_to=event.models.event.event_pictures, verbose_name='Imágen Cover'),
        ),
    ]
