# Generated by Django 3.2.7 on 2021-10-07 07:06

from django.db import migrations
import django_resized.forms
import event.models.event_user_registration


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuserregistration',
            name='img_covid_test_result',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[1080, 1920], upload_to=event.models.event_user_registration.picture),
        ),
        migrations.AlterField(
            model_name='eventuserregistration',
            name='img_signed_responsive_letter',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, size=[1080, 1920], upload_to=event.models.event_user_registration.picture),
        ),
    ]
