# Generated by Django 3.2.7 on 2021-10-10 06:36

from django.db import migrations
import django_resized.forms
import event.models.event
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_alter_event_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dress_code',
            field=tinymce.models.HTMLField(blank=True, default='Codigo de vestimenta', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='img_dress_code',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Imágen del codigo de vestimenta', keep_meta=True, null=True, quality=90, size=[1920, 1080], upload_to=event.models.event.event_pictures, verbose_name='Imágen del codigo de vestimenta'),
        ),
        migrations.AddField(
            model_name='event',
            name='img_rules',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Imágen de las reglas / normas', keep_meta=True, null=True, quality=90, size=[1920, 1080], upload_to=event.models.event.event_pictures, verbose_name='Imágen de las reglas / normas'),
        ),
        migrations.AddField(
            model_name='event',
            name='img_travel_allowance',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Imágen de informacion de viaticos', keep_meta=True, null=True, quality=90, size=[1920, 1080], upload_to=event.models.event.event_pictures, verbose_name='Imágen de informacion de viaticos'),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=tinymce.models.HTMLField(blank=True, default='Reglas / Normas', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='travel_allowance',
            field=tinymce.models.HTMLField(blank=True, default='Informacion de viaticos', null=True),
        ),
    ]
