# Generated by Django 3.2.7 on 2021-10-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20211010_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='expositor',
            name='hidden',
            field=models.BooleanField(default=True, help_text='Define si la/el expositor(a) sera visible o no', verbose_name='Ocultar expositor'),
        ),
    ]
